### ISSUE TITLE
No check for pip version results in failed command

### ISSUE THREAD

**Issue by cocoonkid** [simion/pip-upgrader#21]
pipupgrade
Checking...
Traceback (most recent call last):
  File "/Users/cocoonkid/.pyenv/versions/3.7.1/bin/pipupgrade", line 10, in <module>
    sys.exit(main())
  File "/Users/cocoonkid/.pyenv/versions/3.7.1/lib/python3.7/site-packages/pipupgrade/cli/__init__.py", line 14, in wrapper
    return fn(**params)
  File "/Users/cocoonkid/.pyenv/versions/3.7.1/lib/python3.7/site-packages/pipupgrade/commands/__init__.py", line 178, in command
    format = "json", pip_exec = pip_)
  File "/Users/cocoonkid/.pyenv/versions/3.7.1/lib/python3.7/site-packages/pipupgrade/_pip.py", line 69, in call
    return popen(*params, output = True)
  File "/Users/cocoonkid/.pyenv/versions/3.7.1/lib/python3.7/site-packages/pipupgrade/util/system.py", line 70, in popen
    raise sp.CalledProcessError(code, command)
subprocess.CalledProcessError: Command '/Users/cocoonkid/.pyenv/shims/pip2 list --outdated --format json' returned non-zero exit status 127.

The command should run pip3 list --outdated --format json

Thank you for this great tool!

**Comment by cocoonkid** [comment]
Wrong project ;-)
