### ISSUE TITLE
Python3.7.4 problem 

### ISSUE THREAD

**Issue by cyberamz** [simion/pip-upgrader#22]
Traceback (most recent call last):
  File "/Users/fulgerulnegru/.virtualenvs/cyber7/lib/python3.7/site-packages/pip_upgrader/packages_status_detector.py", line 15, in <module>
    from pip.locations import site_config_files
ModuleNotFoundError: No module named 'pip.locations'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fulgerulnegru/.virtualenvs/cyber7/bin/pip-upgrade", line 6, in <module>
    from pip_upgrader.cli import main
  File "/Users/fulgerulnegru/.virtualenvs/cyber7/lib/python3.7/site-packages/pip_upgrader/cli.py", line 37, in <module>
    from pip_upgrader.packages_status_detector import PackagesStatusDetector
  File "/Users/fulgerulnegru/.virtualenvs/cyber7/lib/python3.7/site-packages/pip_upgrader/packages_status_detector.py", line 17, in <module>
    from pip._internal.locations import site_config_files
ImportError: cannot import name 'site_config_files' from 'pip._internal.locations' (/Users/fulgerulnegru/.virtualenvs/cyber7/lib/python3.7/site-packages/pip/_internal/locations.py)
(cyber7) 192-168-0-240:cyber fulgerulnegru$ pip-upgrade
Traceback (most recent call last):
  File "/Users/fulgerulnegru/.virtualenvs/cyber7/lib/python3.7/site-packages/pip_upgrader/packages_status_detector.py", line 15, in <module>
    from pip.locations import site_config_files
ModuleNotFoundError: No module named 'pip.locations'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fulgerulnegru/.virtualenvs/cyber7/bin/pip-upgrade", line 6, in <module>
    from pip_upgrader.cli import main
  File "/Users/fulgerulnegru/.virtualenvs/cyber7/lib/python3.7/site-packages/pip_upgrader/cli.py", line 37, in <module>
    from pip_upgrader.packages_status_detector import PackagesStatusDetector
  File "/Users/fulgerulnegru/.virtualenvs/cyber7/lib/python3.7/site-packages/pip_upgrader/packages_status_detector.py", line 17, in <module>
    from pip._internal.locations import site_config_files
ImportError: cannot import name 'site_config_files' from 'pip._internal.locations' (/Users/fulgerulnegru/.virtualenvs/cyber7/lib/python3.7/site-packages/pip/_internal/locations.py)
pip freeze
activecampaign-python==0.1.1
amqp==2.5.1
asn1crypto==0.24.0
attrs==19.1.0
Automat==0.7.0
Babel==2.7.0
backports.csv==1.0.7
beautifulsoup4==4.8.0
billiard==3.5.0.5
cairocffi==1.0.2
CairoSVG==2.4.1
celery==4.2.1
certifi==2019.6.16
cffi==1.12.3
chardet==3.0.4
colorclass==2.2.0
constantly==15.1.0
crochet==1.10.0
cryptography==2.7
cssselect==1.1.0
cssselect2==0.2.1
defusedxml==0.6.0
dicttoxml==1.7.4
diff-match-patch==20181111
Django==2.1.7
django-allauth==0.39.1
django-appconf==1.0.3
django-celery==3.2.2
django-celery-beat==1.4.0
django-ckeditor==5.6.1
django-compressor==2.2
django-environ==0.4.5
django-filter==2.1.0
django-import-export==1.2.0
django-js-asset==1.2.2
django-pipeline==1.6.14
django-rest-auth==0.9.3
django-select2==6.3.1
django-settings-export==1.2.1
django-simple-history==2.4.0
django-sslserver==0.20
django-suit==0.2.26
django-suit-daterange-filter==0.0.6
django-suit-redactor==0.0.4
django-suit-sortable==0.1.0
django-test-plus==1.1.1
django-timezone-field==3.0
djangorestframework==3.9.1
docopt==0.6.2
entrypoints==0.3
et-xmlfile==1.0.1
fake-useragent==0.1.11
flake8==3.7.7
flower==0.9.2
gunicorn==19.9.0
html5lib==1.0.1
hyperlink==19.0.0
idna==2.8
incremental==17.5.0
jdcal==1.4.1
kombu==4.3.0
lxml==4.4.1
mailchimp3==3.0.6
Markdown==3.0.1
mccabe==0.6.1
oauthlib==3.1.0
odfpy==1.4.0
openpyxl==2.6.3
packaging==19.1
parsel==1.5.2
paypalrestsdk==1.13.1
Pillow==5.4.1
pip-upgrader==1.4.6
progressbar2==3.39.2
psycopg2==2.7.7
psycopg2-binary==2.7.7
pyasn1==0.4.6
pyasn1-modules==0.2.6
pycodestyle==2.5.0
pycparser==2.19
PyDispatcher==2.0.5
pyflakes==2.1.1
Pygments==2.4.2
PyHamcrest==1.9.0
pyOpenSSL==19.0.0
pyparsing==2.4.2
Pyphen==0.9.5
python-crontab==2.3.8
python-dateutil==2.8.0
python-memcached==1.59
python-utils==2.3.0
python3-openid==3.1.0
pytz==2019.2
PyYAML==5.1.2
queuelib==1.5.0
raven==6.10.0
rcssmin==1.0.6
requests==2.21.0
requests-oauthlib==1.2.0
rjsmin==1.0.12
Scrapy==1.4.0
scrapy-amazon-robot-middleware3==0.2.2
scrapy-splash==0.7.2
scrapydo==0.2.2
selenium==3.141.0
service-identity==18.1.0
simplejson==3.16.0
six==1.12.0
smartbill-sdk==0.2.6
soupsieve==1.9.3
tablib==0.13.0
terminaltables==3.1.0
tinycss2==1.0.2
tornado==5.1.1
Twisted==18.9.0
urllib3==1.24.3
vine==1.3.0
w3lib==1.21.0
WeasyPrint==45
webencodings==0.5.1
wrapt==1.11.2
xlrd==1.2.0
xlwt==1.3.0
zope.interface==4.6.0

**Comment by cyberamz** [comment]
it's solve install new version pip-upgrade
